/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of InternalServer
 */
interface InternalServer {
  error: string;
  status: number;
}

export class InternalServerError extends ApiError<InternalServer> {}
