/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of NotFound
 */
interface NotFound {
  error: string;
  status: number;
}

export class NotFoundError extends ApiError<NotFound> {}
