/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Unauthorized
 */
interface Unauthorized {
  error: string;
  status: number;
}

export class UnauthorizedError extends ApiError<Unauthorized> {}
