/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Response4, response4Schema } from './response4';

export interface AnArrayOfTemplateObjects {
  response: Response4[];
}

export const anArrayOfTemplateObjectsSchema: Schema<AnArrayOfTemplateObjects> = object(
  { response: ['response', array(lazy(() => response4Schema))] }
);
