/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Component {
  cls: string;
  id: string;
  width: number;
  height: number;
  top: number;
  left: number;
  zindex: number;
  value: string;
  dataIndex: string;
}

export const componentSchema: Schema<Component> = object({
  cls: ['cls', string()],
  id: ['id', string()],
  width: ['width', number()],
  height: ['height', number()],
  top: ['top', number()],
  left: ['left', number()],
  zindex: ['zindex', number()],
  value: ['value', string()],
  dataIndex: ['dataIndex', string()],
});
