/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Data {
  key?: string;
  key2?: string;
}

export const dataSchema: Schema<Data> = object({
  key: ['key', optional(string())],
  key2: ['key2', optional(string())],
});
