/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Meta, metaSchema } from './meta';

export interface DocumentData {
  response: string;
  meta: Meta;
}

export const documentDataSchema: Schema<DocumentData> = object({
  response: ['response', string()],
  meta: ['meta', lazy(() => metaSchema)],
});
