/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema } from '../schema';
import { Data, dataSchema } from './data';

export interface GenerateDocumentMultipleTemplatesRequest {
  template: number;
  data: Data;
}

export const generateDocumentMultipleTemplatesRequestSchema: Schema<GenerateDocumentMultipleTemplatesRequest> = object(
  { template: ['template', number()], data: ['data', lazy(() => dataSchema)] }
);
