/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import { Margins, marginsSchema } from './margins';
import { RepeatLayout, repeatLayoutSchema } from './repeatLayout';

export interface Layout1 {
  format: string;
  width: number;
  height: number;
  unit: string;
  orientation: string;
  rotaion: number;
  margins: Margins;
  repeatLayout: RepeatLayout;
  emptyLabels: number;
}

export const layout1Schema: Schema<Layout1> = object({
  format: ['format', string()],
  width: ['width', number()],
  height: ['height', number()],
  unit: ['unit', string()],
  orientation: ['orientation', string()],
  rotaion: ['rotaion', number()],
  margins: ['margins', lazy(() => marginsSchema)],
  repeatLayout: ['repeatLayout', lazy(() => repeatLayoutSchema)],
  emptyLabels: ['emptyLabels', number()],
});
