/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface Margins {
  top: number;
  right: number;
  bottom: number;
  left: number;
}

export const marginsSchema: Schema<Margins> = object({
  top: ['top', number()],
  right: ['right', number()],
  bottom: ['bottom', number()],
  left: ['left', number()],
});
