/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface Margins1 {
  right: number;
  bottom: number;
}

export const margins1Schema: Schema<Margins1> = object({
  right: ['right', number()],
  bottom: ['bottom', number()],
});
