/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Meta {
  name: string;
  displayName: string;
  encoding: string;
  contentType: string;
}

export const metaSchema: Schema<Meta> = object({
  name: ['name', string()],
  displayName: ['display_name', string()],
  encoding: ['encoding', string()],
  contentType: ['content-type', string()],
});
