/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema } from '../schema';
import { Component, componentSchema } from './component';
import { Margins1, margins1Schema } from './margins1';

export interface Page {
  width: number;
  height: number;
  margins: Margins1;
  components: Component[];
}

export const pageSchema: Schema<Page> = object({
  width: ['width', number()],
  height: ['height', number()],
  margins: ['margins', lazy(() => margins1Schema)],
  components: ['components', array(lazy(() => componentSchema))],
});
