/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface RepeatLayout {
  format: string;
  width: number;
  height: number;
}

export const repeatLayoutSchema: Schema<RepeatLayout> = object({
  format: ['format', string()],
  width: ['width', number()],
  height: ['height', number()],
});
