/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  Schema,
  string,
  unknown,
} from '../schema';
import { Editor, editorSchema } from './editor';
import { Layout, layoutSchema } from './layout';
import { Page, pageSchema } from './page';

export interface Response {
  id: number;
  name: string;
  tags: string[];
  isDraft: boolean;
  layout: Layout;
  pages: Page[];
  dataSettings?: unknown;
  editor: Editor;
}

export const responseSchema: Schema<Response> = object({
  id: ['id', number()],
  name: ['name', string()],
  tags: ['tags', array(string())],
  isDraft: ['isDraft', boolean()],
  layout: ['layout', lazy(() => layoutSchema)],
  pages: ['pages', array(lazy(() => pageSchema))],
  dataSettings: ['dataSettings', unknown()],
  editor: ['editor', lazy(() => editorSchema)],
});
