/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

export interface Response2 {
  success: boolean;
}

export const response2Schema: Schema<Response2> = object({
  success: ['success', boolean()],
});
