/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface Response6 {
  id: number;
  identifier: string;
  isMasterWorkspace: boolean;
  createdAt: string;
}

export const response6Schema: Schema<Response6> = object({
  id: ['id', number()],
  identifier: ['identifier', string()],
  isMasterWorkspace: ['is_master_workspace', boolean()],
  createdAt: ['created_at', string()],
});
