/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, number, object, Schema, string } from '../schema';

export interface Response4 {
  id: number;
  name: string;
  owner: boolean;
  modified: string;
  tags: string[];
}

export const response4Schema: Schema<Response4> = object({
  id: ['id', number()],
  name: ['name', string()],
  owner: ['owner', boolean()],
  modified: ['modified', string()],
  tags: ['tags', array(string())],
});
