/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ReturnsAnURLWhichYouCanUseToRedirectYourUserToTheEditorOrUseAsIframeSource {
  response: string;
}

export const returnsAnURLWhichYouCanUseToRedirectYourUserToTheEditorOrUseAsIframeSourceSchema: Schema<ReturnsAnURLWhichYouCanUseToRedirectYourUserToTheEditorOrUseAsIframeSource> = object(
  { response: ['response', string()] }
);
