/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Response, responseSchema } from './response';

export interface TemplateConfigurationAsJSONObject {
  response: Response;
}

export const templateConfigurationAsJSONObjectSchema: Schema<TemplateConfigurationAsJSONObject> = object(
  { response: ['response', lazy(() => responseSchema)] }
);
