/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Response2, response2Schema } from './response2';

export interface TheRequestWasSuccessfullyExecuted {
  response: Response2;
}

export const theRequestWasSuccessfullyExecutedSchema: Schema<TheRequestWasSuccessfullyExecuted> = object(
  { response: ['response', lazy(() => response2Schema)] }
);
