/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, lazy, object, Schema, string } from '../schema';
import { Layout1, layout1Schema } from './layout1';
import { Page, pageSchema } from './page';

export interface UpdateTemplateRequest {
  name: string;
  tags: string[];
  isDraft: boolean;
  layout: Layout1;
  pages: Page[];
}

export const updateTemplateRequestSchema: Schema<UpdateTemplateRequest> = object(
  {
    name: ['name', string()],
    tags: ['tags', array(string())],
    isDraft: ['isDraft', boolean()],
    layout: ['layout', lazy(() => layout1Schema)],
    pages: ['pages', array(lazy(() => pageSchema))],
  }
);
