/**
 * PDF Generator API 3.1.1Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Response6, response6Schema } from './response6';

export interface WorkspaceInformation {
  response: Response6;
}

export const workspaceInformationSchema: Schema<WorkspaceInformation> = object({
  response: ['response', lazy(() => response6Schema)],
});
